networks:
  default:
    driver: bridge
services:
  app:
    build: .
    labels:
    - nginx.host_port=5124
    - nginx.container_port=3000
    networks:
    - default
    ports:
    - 5124:3000
    environment:
    - FLASK_ENV=production
    restart: unless-stopped
version: '3.9'
