name: Build and Deploy Docker Compose

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-

    - name: Build and push Docker images
      run: |
        # Update image names in docker-compose.yml to use GHCR
        sed -i 's|image: \([^/]*\)$|image: ${{ env.REGISTRY }}/${{ github.repository }}/\1:${{ github.sha }}|g' docker-compose.yml
        
        # Build and push images
        docker compose build
        docker compose push

    - name: Deploy to server
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        curl -X POST "https://deployment.jonasreitz.de/webhook/github" \
          -H "Content-Type: application/json" \
          -d '{{            "repository": {{              "clone_url": "${{ github.server_url }}/${{ github.repository }}.git",              "name": "testproject4"            }},            "ref": "${{ github.ref }}"          }}'
